/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ProductVariant = {
  _id: string;
  _type: "productVariant";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seo?: Seo;
  productTitle?: string;
  variantTitle?: string;
  productID?: number;
  variantID?: number;
  price?: number;
  comparePrice?: number;
  inStock?: boolean;
  lowStock?: boolean;
  sku?: string;
  options?: Array<
    {
      _key: string;
    } & ProductOptionValue
  >;
  isDraft?: boolean;
  wasDeleted?: boolean;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDesc?: string;
  shareTitle?: string;
  shareDesc?: string;
  shareGraphic?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type ProductGalleryPhotos = {
  _type: "productGalleryPhotos";
  forOption?: string;
  photos?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    customRatio?: 0 | 1 | 0.7142857143 | 0.6666666667 | 1.7777777778;
    alt?: string;
    _type: "photo";
    _key: string;
  }>;
};

export type ProductOptionSettings = {
  _type: "productOptionSettings";
  forOption?: string;
  color?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "solidColor";
  };
};

export type SolidColor = {
  _id: string;
  _type: "solidColor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  color?: Color;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type ProductOptionValue = {
  _type: "productOptionValue";
  name?: string;
  value?: string;
  position?: number;
};

export type ProductOption = {
  _type: "productOption";
  name?: string;
  position?: number;
  values?: Array<string>;
};

export type Promo = {
  _id: string;
  _type: "promo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  enabled?: boolean;
  text?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
>;

export type Collection = {
  _id: string;
  _type: "collection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  products?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "product";
  }>;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  shopifyDescription?: string;
  description?: BlockContent;
  optionSettings?: Array<
    {
      _key: string;
    } & ProductOptionSettings
  > | null;
  seo?: Seo;
  galleryPhotos?: Array<
    {
      _key: string;
    } & ProductGalleryPhotos
  >;
  productTitle?: string;
  productID?: number;
  productImage?: string;
  price?: number;
  comparePrice?: number;
  inStock?: boolean;
  lowStock?: boolean;
  sku?: string;
  slug?: Slug;
  options?: Array<
    {
      _key: string;
    } & ProductOption
  >;
  isDraft?: boolean;
  wasDeleted?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ProductVariant
  | Seo
  | ProductGalleryPhotos
  | ProductOptionSettings
  | SolidColor
  | Color
  | ProductOptionValue
  | ProductOption
  | Promo
  | BlockContent
  | Collection
  | Slug
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/banner/getPromoBanner.ts
// Variable: ACTIVE_PROMO_BANNER
// Query: *[_type == "promo"][0]{                enabled,                text            }
export type ACTIVE_PROMO_BANNERResult = {
  enabled: boolean | null;
  text: string | null;
} | null;

// Source: ./src/sanity/lib/products/getAllCategories.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[_type== "category"] | order(name asc)
export type ALL_CATEGORIES_QUERYResult = Array<never>;

// Source: ./src/sanity/lib/products/getAllProducts.ts
// Variable: ALL_PRODUCTS_QUERY
// Query: *[_type == "product" && !wasDeleted] | order(productTitle asc) {      ...,      optionSettings,      "optionSettingsResolved": optionSettings[]{        forOption,        "color": color->color      },     "variants": *[_type == "productVariant" && string(productID) == string(^.productID) ] {        ...,      }    }
export type ALL_PRODUCTS_QUERYResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  shopifyDescription?: string;
  description?: BlockContent;
  optionSettings: Array<
    {
      _key: string;
    } & ProductOptionSettings
  > | null;
  seo?: Seo;
  galleryPhotos?: Array<
    {
      _key: string;
    } & ProductGalleryPhotos
  >;
  productTitle?: string;
  productID?: number;
  productImage?: string;
  price?: number;
  comparePrice?: number;
  inStock?: boolean;
  lowStock?: boolean;
  sku?: string;
  slug?: Slug;
  options?: Array<
    {
      _key: string;
    } & ProductOption
  >;
  isDraft?: boolean;
  wasDeleted?: boolean;
  optionSettingsResolved: Array<{
    forOption: string | null;
    color: Color | null;
  }> | null;
  variants: Array<{
    _id: string;
    _type: "productVariant";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    seo?: Seo;
    productTitle?: string;
    variantTitle?: string;
    productID?: number;
    variantID?: number;
    price?: number;
    comparePrice?: number;
    inStock?: boolean;
    lowStock?: boolean;
    sku?: string;
    options?: Array<
      {
        _key: string;
      } & ProductOptionValue
    >;
    isDraft?: boolean;
    wasDeleted?: boolean;
  }>;
}>;

// Source: ./src/sanity/lib/products/getProductBySlug.ts
// Variable: PRODUCT_BY_ID_QUERY
// Query: *[_type == "product" && slug.current == $slug] | order(name asc)[0]{      ...,      optionSettings,      "optionSettingsResolved": optionSettings[]{        forOption,        "color": color->color      },        "variants": *[_type == "productVariant" && string(productID) == string(^.productID) ] {        ...,      }  }
export type PRODUCT_BY_ID_QUERYResult = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  shopifyDescription?: string;
  description?: BlockContent;
  optionSettings: Array<
    {
      _key: string;
    } & ProductOptionSettings
  > | null;
  seo?: Seo;
  galleryPhotos?: Array<
    {
      _key: string;
    } & ProductGalleryPhotos
  >;
  productTitle?: string;
  productID?: number;
  productImage?: string;
  price?: number;
  comparePrice?: number;
  inStock?: boolean;
  lowStock?: boolean;
  sku?: string;
  slug?: Slug;
  options?: Array<
    {
      _key: string;
    } & ProductOption
  >;
  isDraft?: boolean;
  wasDeleted?: boolean;
  optionSettingsResolved: Array<{
    forOption: string | null;
    color: Color | null;
  }> | null;
  variants: Array<{
    _id: string;
    _type: "productVariant";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    seo?: Seo;
    productTitle?: string;
    variantTitle?: string;
    productID?: number;
    variantID?: number;
    price?: number;
    comparePrice?: number;
    inStock?: boolean;
    lowStock?: boolean;
    sku?: string;
    options?: Array<
      {
        _key: string;
      } & ProductOptionValue
    >;
    isDraft?: boolean;
    wasDeleted?: boolean;
  }>;
} | null;

// Source: ./src/sanity/lib/products/searchProductsByName.ts
// Variable: PRODUCT_SEARCH_QUERY
// Query: *[_type == "product" && productTitle match $searchParam] | order(productTitle asc)
export type PRODUCT_SEARCH_QUERYResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  shopifyDescription?: string;
  description?: BlockContent;
  optionSettings?: Array<
    {
      _key: string;
    } & ProductOptionSettings
  >;
  seo?: Seo;
  galleryPhotos?: Array<
    {
      _key: string;
    } & ProductGalleryPhotos
  >;
  productTitle?: string;
  productID?: number;
  productImage?: string;
  price?: number;
  comparePrice?: number;
  inStock?: boolean;
  lowStock?: boolean;
  sku?: string;
  slug?: Slug;
  options?: Array<
    {
      _key: string;
    } & ProductOption
  >;
  isDraft?: boolean;
  wasDeleted?: boolean;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n            *[_type == "promo"][0]{\n                enabled,\n                text\n            }\n        ': ACTIVE_PROMO_BANNERResult;
    '*[_type== "category"] | order(name asc)': ALL_CATEGORIES_QUERYResult;
    '*[_type == "product" && !wasDeleted] | order(productTitle asc) {\n      ...,\n      optionSettings,\n      "optionSettingsResolved": optionSettings[]{\n        forOption,\n        "color": color->color\n      },\n     "variants": *[_type == "productVariant" && string(productID) == string(^.productID) ] {\n        ...,\n      }\n    }': ALL_PRODUCTS_QUERYResult;
    '\n    *[_type == "product" && slug.current == $slug] | order(name asc)[0]{\n      ...,\n      optionSettings,\n      "optionSettingsResolved": optionSettings[]{\n        forOption,\n        "color": color->color\n      },\n        "variants": *[_type == "productVariant" && string(productID) == string(^.productID) ] {\n        ...,\n      }\n  }\n    ': PRODUCT_BY_ID_QUERYResult;
    '*[_type == "product" && productTitle match $searchParam] | order(productTitle asc)': PRODUCT_SEARCH_QUERYResult;
  }
}
