/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Video = {
  id?: string;
  title?: string;
};

export type InfoPage = {
  _id: string;
  _type: "infoPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  items?: Array<
    {
      _key: string;
    } & InfoBlock
  >;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type InfoBlock = {
  _type: "infoBlock";
  title?: string;
  content?: BlockContent;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
>;

export type InfoPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "infoPage";
};

export type FooterSection = {
  _id: string;
  _type: "footerSection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  order?: number;
  pages?: Array<
    {
      _key: string;
    } & InfoPageReference
  >;
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type ProductVariant = {
  _id: string;
  _type: "productVariant";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  product?: ProductReference;
  seo?: Seo;
  productTitle?: string;
  variantTitle?: string;
  productID?: number;
  variantID?: number;
  price?: number;
  comparePrice?: number;
  inStock?: boolean;
  lowStock?: boolean;
  sku?: string;
  options?: Array<
    {
      _key: string;
    } & ProductOptionValue
  >;
  isDraft?: boolean;
  wasDeleted?: boolean;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDesc?: string;
  shareTitle?: string;
  shareDesc?: string;
  shareGraphic?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type ProductGalleryPhotos = {
  _type: "productGalleryPhotos";
  forOption?: string;
  photos?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    customRatio?: 0 | 1 | 0.7142857143 | 0.6666666667 | 1.7777777778;
    alt?: string;
    _type: "photo";
    _key: string;
  }>;
};

export type SolidColorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "solidColor";
};

export type ProductOptionSettings = {
  _type: "productOptionSettings";
  forOption?: string;
  color?: SolidColorReference;
};

export type SolidColor = {
  _id: string;
  _type: "solidColor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  color?: Color;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type ProductOptionValue = {
  _type: "productOptionValue";
  name?: string;
  value?: string;
  position?: number;
};

export type ProductOption = {
  _type: "productOption";
  name?: string;
  position?: number;
  values?: Array<string>;
};

export type Promo = {
  _id: string;
  _type: "promo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  enabled?: boolean;
  text?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type DividerMediaItem = {
  _type: "dividerMediaItem";
  mediaType?: "image" | "video";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    customRatio?: 0 | 1 | 0.7142857143 | 0.6666666667 | 1.7777777778;
    alt?: string;
    _type: "image";
  };
  video?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type DividerPhoto = {
  _type: "dividerPhoto";
  media?: Array<
    {
      _key: string;
    } & DividerMediaItem
  >;
};

export type Marquee = {
  _type: "marquee";
  items?: Array<
    | {
        text?: string;
        _type: "simple";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        customRatio?: 0 | 1 | 0.7142857143 | 0.6666666667 | 1.7777777778;
        alt?: string;
        _type: "photo";
        _key: string;
      }
    | ({
        _key: string;
      } & ProductReference)
  >;
  speed?: number;
  reverse?: boolean;
  pausable?: boolean;
};

export type Section = {
  _id: string;
  _type: "section";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  content?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & Marquee)
    | ({
        _key: string;
      } & DividerPhoto)
  >;
};

export type Hero = {
  _type: "hero";
  bgType?: "photo" | "video";
  photos?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    customRatio?: 0 | 1 | 0.7142857143 | 0.6666666667 | 1.7777777778;
    alt?: string;
    _type: "photo";
    _key: string;
  }>;
  video?: Video;
};

export type SectionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "section";
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  hasTransparentHeader?: boolean;
  modules?: Array<
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & Marquee)
    | ({
        _key: string;
      } & DividerPhoto)
    | ({
        _key: string;
      } & SectionReference)
  >;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type CollectionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "collection";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  shopifyDescription?: string;
  primaryCollection?: CollectionReference;
  description?: BlockContent;
  optionSettings?: Array<
    {
      _key: string;
    } & ProductOptionSettings
  >;
  seo?: Seo;
  galleryPhotos?: Array<
    {
      _key: string;
    } & ProductGalleryPhotos
  >;
  productTitle?: string;
  productID?: number;
  productImage?: string;
  price?: number;
  comparePrice?: number;
  inStock?: boolean;
  lowStock?: boolean;
  sku?: string;
  slug?: Slug;
  options?: Array<
    {
      _key: string;
    } & ProductOption
  >;
  isDraft?: boolean;
  wasDeleted?: boolean;
};

export type Collection = {
  _id: string;
  _type: "collection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  products?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  seo?: Seo;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Video
  | InfoPage
  | Slug
  | InfoBlock
  | SanityImageAssetReference
  | BlockContent
  | InfoPageReference
  | FooterSection
  | ProductReference
  | ProductVariant
  | Seo
  | ProductGalleryPhotos
  | SolidColorReference
  | ProductOptionSettings
  | SolidColor
  | Color
  | ProductOptionValue
  | ProductOption
  | Promo
  | SanityFileAssetReference
  | DividerMediaItem
  | DividerPhoto
  | Marquee
  | Section
  | Hero
  | SectionReference
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | CollectionReference
  | Product
  | Collection
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/banner/getPromoBanner.ts
// Variable: ACTIVE_PROMO_BANNER
// Query: *[_type == "promo"]{                enabled,                text            }
export type ACTIVE_PROMO_BANNER_RESULT = Array<{
  enabled: boolean | null;
  text: string | null;
}>;

// Source: src/sanity/lib/getHomepage.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_type == "page" && slug.current == "home"][0]{      ...,      seo {        metaTitle,        metaDesc,        shareTitle,        shareDesc,        shareGraphic {          asset->{            _id,            url          }        }      },     }
export type HOMEPAGE_QUERY_RESULT = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  hasTransparentHeader?: boolean;
  modules?: Array<
    | ({
        _key: string;
      } & DividerPhoto)
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & Marquee)
    | ({
        _key: string;
      } & SectionReference)
  >;
  seo: {
    metaTitle: string | null;
    metaDesc: string | null;
    shareTitle: string | null;
    shareDesc: string | null;
    shareGraphic: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/products/getAllCollections.ts
// Variable: ALL_COLLECTIONS
// Query: *[_type== "collection"] | order(title desc){      _id,      _type,      _createdAt,      updatedAt,            title,      "slug": slug.current    }
export type ALL_COLLECTIONS_RESULT = Array<{
  _id: string;
  _type: "collection";
  _createdAt: string;
  updatedAt: null;
  title: string | null;
  slug: string | null;
}>;

// Source: src/sanity/lib/products/getAllProducts.ts
// Variable: ALL_PRODUCTS_QUERY
// Query: *[_type == "product" && !wasDeleted && defined(slug.current)] {        "slug": slug.current    }
export type ALL_PRODUCTS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/lib/products/getAllProducts.ts
// Variable: NEW_COLLECTION_QUERY
// Query: *[_type == "collection" && slug.current == $slug][0] {        title,        "slug": slug.current,        "products": products[]->{          ...,          optionSettings,          "optionSettingsResolved": optionSettings[]{            forOption,            "color": color->color          },          "variants": *[_type == "productVariant" && string(productID) == string(^.productID)  && wasDeleted != true ] {        ...,         }        }    }
export type NEW_COLLECTION_QUERY_RESULT = {
  title: string | null;
  slug: string | null;
  products: Array<{
    _id: string;
    _type: "product";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    shopifyDescription?: string;
    primaryCollection?: CollectionReference;
    description?: BlockContent;
    optionSettings: Array<
      {
        _key: string;
      } & ProductOptionSettings
    > | null;
    seo?: Seo;
    galleryPhotos?: Array<
      {
        _key: string;
      } & ProductGalleryPhotos
    >;
    productTitle?: string;
    productID?: number;
    productImage?: string;
    price?: number;
    comparePrice?: number;
    inStock?: boolean;
    lowStock?: boolean;
    sku?: string;
    slug?: Slug;
    options?: Array<
      {
        _key: string;
      } & ProductOption
    >;
    isDraft?: boolean;
    wasDeleted?: boolean;
    optionSettingsResolved: Array<{
      forOption: string | null;
      color: Color | null;
    }> | null;
    variants: Array<{
      _id: string;
      _type: "productVariant";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      product?: ProductReference;
      seo?: Seo;
      productTitle?: string;
      variantTitle?: string;
      productID?: number;
      variantID?: number;
      price?: number;
      comparePrice?: number;
      inStock?: boolean;
      lowStock?: boolean;
      sku?: string;
      options?: Array<
        {
          _key: string;
        } & ProductOptionValue
      >;
      isDraft?: boolean;
      wasDeleted?: boolean;
    }>;
  }> | null;
} | null;

// Source: src/sanity/lib/products/getProductByID.ts
// Variable: query
// Query: *[_type == "product" && productID == $productID && wasDeleted != true][0]{     ...,     "variants": *[_type == "productVariant" && string(productID) == string(^.productID) && wasDeleted != true ] {        ...,      },       }
export type QueryResult = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  shopifyDescription?: string;
  primaryCollection?: CollectionReference;
  description?: BlockContent;
  optionSettings?: Array<
    {
      _key: string;
    } & ProductOptionSettings
  >;
  seo?: Seo;
  galleryPhotos?: Array<
    {
      _key: string;
    } & ProductGalleryPhotos
  >;
  productTitle?: string;
  productID?: number;
  productImage?: string;
  price?: number;
  comparePrice?: number;
  inStock?: boolean;
  lowStock?: boolean;
  sku?: string;
  slug?: Slug;
  options?: Array<
    {
      _key: string;
    } & ProductOption
  >;
  isDraft?: boolean;
  wasDeleted?: boolean;
  variants: Array<{
    _id: string;
    _type: "productVariant";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    product?: ProductReference;
    seo?: Seo;
    productTitle?: string;
    variantTitle?: string;
    productID?: number;
    variantID?: number;
    price?: number;
    comparePrice?: number;
    inStock?: boolean;
    lowStock?: boolean;
    sku?: string;
    options?: Array<
      {
        _key: string;
      } & ProductOptionValue
    >;
    isDraft?: boolean;
    wasDeleted?: boolean;
  }>;
} | null;

// Source: src/sanity/lib/products/getProductBySlug.ts
// Variable: PRODUCT_BY_ID_QUERY
// Query: *[_type == "product" && slug.current == $slug] | order(name asc)[0]{      ...,      optionSettings,      seo {        metaTitle,        metaDesc,        shareTitle,        shareDesc,        shareGraphic {          asset->{            _id,            url          }        }      },      "optionSettingsResolved": optionSettings[]{        forOption,        "color": color->color      },        "variants": *[_type == "productVariant" && string(productID) == string(^.productID) && wasDeleted != true ] {        ...,      },     }
export type PRODUCT_BY_ID_QUERY_RESULT = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  shopifyDescription?: string;
  primaryCollection?: CollectionReference;
  description?: BlockContent;
  optionSettings: Array<
    {
      _key: string;
    } & ProductOptionSettings
  > | null;
  seo: {
    metaTitle: string | null;
    metaDesc: string | null;
    shareTitle: string | null;
    shareDesc: string | null;
    shareGraphic: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
    } | null;
  } | null;
  galleryPhotos?: Array<
    {
      _key: string;
    } & ProductGalleryPhotos
  >;
  productTitle?: string;
  productID?: number;
  productImage?: string;
  price?: number;
  comparePrice?: number;
  inStock?: boolean;
  lowStock?: boolean;
  sku?: string;
  slug?: Slug;
  options?: Array<
    {
      _key: string;
    } & ProductOption
  >;
  isDraft?: boolean;
  wasDeleted?: boolean;
  optionSettingsResolved: Array<{
    forOption: string | null;
    color: Color | null;
  }> | null;
  variants: Array<{
    _id: string;
    _type: "productVariant";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    product?: ProductReference;
    seo?: Seo;
    productTitle?: string;
    variantTitle?: string;
    productID?: number;
    variantID?: number;
    price?: number;
    comparePrice?: number;
    inStock?: boolean;
    lowStock?: boolean;
    sku?: string;
    options?: Array<
      {
        _key: string;
      } & ProductOptionValue
    >;
    isDraft?: boolean;
    wasDeleted?: boolean;
  }>;
} | null;

// Source: src/sanity/lib/products/searchProductsByName.ts
// Variable: PRODUCT_SEARCH_QUERY
// Query: *[_type == "product" && productTitle match $searchParam] | order(productTitle asc) {      ...,       "variants": *[_type == "productVariant" && string(productID) == string(^.productID) ] {        ...,      }    }
export type PRODUCT_SEARCH_QUERY_RESULT = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  shopifyDescription?: string;
  primaryCollection?: CollectionReference;
  description?: BlockContent;
  optionSettings?: Array<
    {
      _key: string;
    } & ProductOptionSettings
  >;
  seo?: Seo;
  galleryPhotos?: Array<
    {
      _key: string;
    } & ProductGalleryPhotos
  >;
  productTitle?: string;
  productID?: number;
  productImage?: string;
  price?: number;
  comparePrice?: number;
  inStock?: boolean;
  lowStock?: boolean;
  sku?: string;
  slug?: Slug;
  options?: Array<
    {
      _key: string;
    } & ProductOption
  >;
  isDraft?: boolean;
  wasDeleted?: boolean;
  variants: Array<{
    _id: string;
    _type: "productVariant";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    product?: ProductReference;
    seo?: Seo;
    productTitle?: string;
    variantTitle?: string;
    productID?: number;
    variantID?: number;
    price?: number;
    comparePrice?: number;
    inStock?: boolean;
    lowStock?: boolean;
    sku?: string;
    options?: Array<
      {
        _key: string;
      } & ProductOptionValue
    >;
    isDraft?: boolean;
    wasDeleted?: boolean;
  }>;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n            *[_type == "promo"]{\n                enabled,\n                text\n            }\n        ': ACTIVE_PROMO_BANNER_RESULT;
    '\n         *[_type == "page" && slug.current == "home"][0]{\n      ...,\n      seo {\n        metaTitle,\n        metaDesc,\n        shareTitle,\n        shareDesc,\n        shareGraphic {\n          asset->{\n            _id,\n            url\n          }\n        }\n      },\n   \n  }\n        ': HOMEPAGE_QUERY_RESULT;
    '*[_type== "collection"] | order(title desc){\n      _id,\n      _type,\n      _createdAt,\n      updatedAt,\n      \n      title,\n      "slug": slug.current\n    }': ALL_COLLECTIONS_RESULT;
    '*[_type == "product" && !wasDeleted && defined(slug.current)] {\n        "slug": slug.current\n    }': ALL_PRODUCTS_QUERY_RESULT;
    '*[_type == "collection" && slug.current == $slug][0] {\n        title,\n        "slug": slug.current,\n        "products": products[]->{\n          ...,\n          optionSettings,\n          "optionSettingsResolved": optionSettings[]{\n            forOption,\n            "color": color->color\n          },\n          "variants": *[_type == "productVariant" && string(productID) == string(^.productID)  && wasDeleted != true ] {\n        ...,\n         }\n        }\n    }': NEW_COLLECTION_QUERY_RESULT;
    '*[_type == "product" && productID == $productID && wasDeleted != true][0]{\n     ...,\n     "variants": *[_type == "productVariant" && string(productID) == string(^.productID) && wasDeleted != true ] {\n        ...,\n      },\n   \n    }': QueryResult;
    '\n    *[_type == "product" && slug.current == $slug] | order(name asc)[0]{\n      ...,\n      optionSettings,\n      seo {\n        metaTitle,\n        metaDesc,\n        shareTitle,\n        shareDesc,\n        shareGraphic {\n          asset->{\n            _id,\n            url\n          }\n        }\n      },\n      "optionSettingsResolved": optionSettings[]{\n        forOption,\n        "color": color->color\n      },\n        "variants": *[_type == "productVariant" && string(productID) == string(^.productID) && wasDeleted != true ] {\n        ...,\n      },\n   \n  }\n    ': PRODUCT_BY_ID_QUERY_RESULT;
    '*[_type == "product" && productTitle match $searchParam] | order(productTitle asc) {\n      ...,\n       "variants": *[_type == "productVariant" && string(productID) == string(^.productID) ] {\n        ...,\n      }\n    }': PRODUCT_SEARCH_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
