import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { SanityLive } from "@/sanity/lib/live";
import Header from "@/components/Header";
import CartInitialize from "@/components/CartInitialize";
import Cart from "@/components/Cart";
import Banner from "@/components/Banner";
import MenuModal from "@/components/modals/menuModal";
import { Footer } from "@/components/Footer";
import Newsletter from "@/components/Newsletter";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const cartId = cookieStore.get("cartId")?.value ?? null;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <main className="text-gray-800">
          <Banner />
          <Header />
          {/*hydrate zustand  */}
          <CartInitialize cartId={cartId} />
          {children}
          <Cart />
        </main>
        <MenuModal />
        <Newsletter />
        <Footer />
        <SanityLive />
      </body>
    </html>
  );
}
