import { CopyIcon } from "@sanity/icons";
import { BsCloudArrowDown } from "react-icons/bs";
import { defineField, defineType } from "sanity";
export const variants = defineType({
  title: "Variant",
  name: "productVariant",
  type: "document",
  icon: CopyIcon,
  groups: [
    { title: "Content", name: "content", default: true },
    { title: "Settings", name: "settings" },
    { title: "Shopify Data", name: "shopify", icon: BsCloudArrowDown },
  ],
  fieldsets: [{ title: "", name: "2up", options: { columns: 2 } }],
  fields: [
    defineField({
      title: "Display Title",
      name: "title",
      type: "string",
      description:
        "Shown where variant names appear (for example: Above the product title in the cart",
      group: "content",
    }),
    defineField({
      title: "SEO / Share Settings",
      name: "seo",
      type: "seo",
      group: "settings",
    }),
    defineField({
      title: "Product Title",
      name: "productTitle",
      type: "string",
      readOnly: true,
      fieldset: "2up",
      group: "shopify",
    }),
    defineField({
      title: "Variant Title",
      name: "variantTitle",
      type: "string",
      readOnly: true,
      fieldset: "2up",
      group: "shopify",
    }),
    defineField({
      title: "Product ID",
      name: "productID",
      type: "number",
      readOnly: true,
      fieldset: "2up",
      group: "shopify",
    }),
    defineField({
      title: "Variant ID",
      name: "variantID",
      type: "number",
      readOnly: true,
      fieldset: "2up",
      group: "shopify",
    }),
    defineField({
      title: "Price (cents)",
      name: "price",
      type: "number",
      readOnly: true,
      fieldset: "2up",
      group: "shopify",
    }),
    defineField({
      title: "Compare Price (cents)",
      name: "comparePrice",
      type: "number",
      readOnly: true,
      fieldset: "2up",
      group: "shopify",
    }),
    defineField({
      title: "In Stock?",
      name: "inStock",
      type: "boolean",
      readOnly: true,
      fieldset: "2up",
      group: "shopify",
    }),
    defineField({
      title: "Low Stock?",
      name: "lowStock",
      type: "boolean",
      readOnly: true,
      fieldset: "2up",
      group: "shopify",
    }),
    defineField({
      title: "SKU",
      name: "sku",
      type: "string",
      readOnly: true,
      fieldset: "2up",
      group: "shopify",
    }),
    defineField({
      title: "Options",
      name: "options",
      type: "array",
      of: [{ type: "productOptionValue" }],
      readOnly: true,
      group: "shopify",
    }),
    defineField({
      title: "Draft Mode",
      name: "isDraft",
      type: "boolean",
      readOnly: true,
      hidden: true,
      fieldset: "2up",
      group: "shopify",
    }),
    defineField({
      title: "Deleted from Shopify",
      name: "wasDeleted",
      type: "boolean",
      readOnly: true,
      hidden: true,
      fieldset: "2up",
      group: "shopify",
    }),
  ],
  preview: {
    select: {
      wasDeleted: "wasDeleted",
      title: "title",
      variantTitle: "variantTitle",
      productTitle: "productTitle",
    },
  },
});
